" 让配置变更立即生效
" autocmd BufWritePost $MYVIMRC source $MYVIMRC

set sw=3 ts=4 nobk ai cin nu
set fileencodings=ucs-bom,utf-8,utf-16,gbk,big5,gb18030,latin1
set encoding=utf-8
set backspace=indent,eol,start

" 关闭兼容模式
set nocompatible

" vundle 配置
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
" vundle 插件列表必须位于 vundle#begin() 和 vundle#end() 之间
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'altercation/vim-colors-solarized'
Plugin 'tomasr/molokai'
Plugin 'Lokaltog/vim-powerline'
Plugin 'octol/vim-cpp-enhanced-highlight'
call vundle#end()
filetype plugin indent on

" 禁止折行
set nowrap

" 关闭错误提示音
set vb t_vb=
autocmd GUIEnter * set visualbell t_vb=

" 配色方案
set background=light
colorscheme molokai

" 语法高亮
syntax enable
syntax on


" 字体
set guifont=Consolas:h14
" set guifontwide=Microsoft\ Yahei\ Mono:h14

" 状态栏风格
let g:Powerline_colorscheme='solarized256'
let g:Powerline_background='light'

" 禁止显示菜单和工具栏
set guioptions-=m
set guioptions-=T

" 禁止光标闪烁
set gcr=a:block-blinkon0

" 不显示工具栏
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R

" 总是显示状态栏
set laststatus=2

" 显示光标位置
set ruler

" 高亮当前行/列
set cursorline
set cursorcolumn

" 高亮搜索结果
set hlsearch

" 实时搜索
set incsearch

" tab映射
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4


let mapleader=";"

map <leader>qw :FixWhitespace<cr>

noremap yy "xyy
noremap dd "xdd
noremap p "xp
noremap y "xy
noremap d "xd
noremap x "xx

" 删除不必要的快捷键
map <C-A> <Nop>
map <C-X> <Nop>
