set sw=3 ts=4 nobk ai cin nu
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set backspace=indent,eol,start

" ??兼容模式
set nocompatible

" vundle ?境?置
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
" vundle 管理的插件列表必?位于 vundle#begin() 和 vundle#end() 之?
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'altercation/vim-colors-solarized'
Plugin 'tomasr/molokai'
"Plugin 'vim-scripts/phd'
Plugin 'Lokaltog/vim-powerline'
Plugin 'octol/vim-cpp-enhanced-highlight'
"Plugin 'nathanaelkane/vim-indent-guides'
"Plugin 'derekwyatt/vim-fswitch'
"Plugin 'kshenoy/vim-signature'
"Plugin 'vim-scripts/BOOKMARKS--Mark-and-Highlight-Full-Lines'
"Plugin 'majutsushi/tagbar'
"Plugin 'vim-scripts/indexer.tar.gz'
"Plugin 'vim-scripts/DfrankUtil'
"Plugin 'vim-scripts/vimprj'
"Plugin 'vim-scripts/DrawIt'
"Plugin 'dyng/ctrlsf.vim'
"Plugin 'terryma/vim-multiple-cursors'
"Plugin 'scrooloose/nerdcommenter'
"Plugin 'SirVer/ultisnips'
"Plugin 'Valloric/YouCompleteMe'
"Plugin 'derekwyatt/vim-protodef'
"Plugin 'scrooloose/nerdtree'
"Plugin 'fholgado/minibufexpl.vim'
"Plugin 'gcmt/wildfire.vim'
"Plugin 'sjl/gundo.vim'
"Plugin 'Lokaltog/vim-easymotion'
"Plugin 'suan/vim-instant-markdown'
"Plugin 'lilydjwg/fcitx.vim'
" 插件列表?束
call vundle#end()
filetype plugin indent on

" 禁止折行
set nowrap

" ????提示音
" 特?的, vim????刷新t_vb, 需要在vim??之后?制重新?一下t_vb, 否?每次重?都??回去
set vb t_vb=
autocmd GUIEnter * set visualbell t_vb=

" 配色方案
" set background=dark
set background=light
"colorscheme solarized
colorscheme molokai
"colorscheme phd

" ???法高亮功能
syntax enable
" 允?用指定?法高亮配色方案替?默?方案
syntax on


" 字体
"set guifont=黑体:h12:cGB2312
"set guifont=Consolas:h10
" ?字?字体?置(也就是英文字体)
set guifont=Consolas:h14
" ?字?字体?置(也就是中文字体)
set guifontwide=Microsoft\ Yahei\ Mono:h14

" 禁用鼠?
set mouse-=a

" 自??用配置
autocmd BufWritePost $MYVIMRC source $MYVIMRC

" ?置???主??格
let g:Powerline_colorscheme='solarized256'
let g:Powerline_background='light'

" 禁止菜?和工具?
set guioptions-=m
set guioptions-=T

" 禁止光???
set gcr=a:block-blinkon0

" 禁止?示???
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R

" ?是?示???
set laststatus=2

" ?示光??前位置
set ruler

" 高亮?前行/列
set cursorline
set cursorcolumn

" 高亮搜索?果
set hlsearch

" ??搜索
set incsearch

" ?制表符?展?空格
set expandtab
" ?置???制表符占用空格?
set tabstop=4
" ?置格式化?制表符占用空格?
set shiftwidth=4
" ? vim 把???量的空格??一?制表符
set softtabstop=4


" 快捷??置
let mapleader=";"

map <leader>qw :FixWhitespace<cr>

" ?除?不使用匿名寄存器
noremap yy "xyy
noremap dd "xdd
noremap p "xp
noremap y "xy
noremap d "xd
noremap x "xx

" >>
" 刪除不需要且容易誤用的快捷?

" ?字的自增自?
map <C-A> <Nop>
map <C-X> <Nop>

